- name: install opensmtpd related packages
  apt:
    name:
      - opensmtpd
      - mailutils

# rtu: why we need to update bios for an smtp relay?
#- name: install python3 pip packages
#  pip:
#    name: bios
#    executable: /usr/bin/pip3
#  with_items:
#    - bios

- name: create config directories
  file:
    state: directory
    name: "{{ mailrelay_opensmtpd_config_directory_item }}"
    owner: root
    group: opensmtpd
    mode: "0750"
  with_items:
    - "/etc/smtpd/tables"
  loop_control:
    loop_var: mailrelay_opensmtpd_config_directory_item

- name: template /etc/smtpd.conf
  template:
    src: templates/etc/smtpd.conf.j2
    dest: /etc/smtpd.conf
    owner: root
    group: opensmtpd
    mode: "0640"
  notify: restart opensmtpd

- name: create script directories for filters
  file:
    state: directory
    name: "{{ mailrelay_opensmtpd_scripts_directory_item }}"
    owner: root
    group: opensmtpd
    mode: "0750"
  with_items:
    - "/etc/smtpd/scripts"
  loop_control:
    loop_var: mailrelay_opensmtpd_scripts_directory_item

- name: create log directory for filters
  file:
    state: directory
    name: "/var/log/opensmtpd"
    owner: root
    group: opensmtpd
    mode: "0660"

- name: filter script /etc/smtpd/scripts/
  template:
    src: templates/etc/scripts/filter_domain.sh.j2
    dest: /etc/smtpd/scripts/filter_domain.sh
    owner: root
    group: opensmtpd
    mode: "0777"
  notify: restart opensmtpd

- name: template /etc/smtpd/tables/relay_secrets
  template:
    src: templates/etc/smtpd/tables/{{ opensmtpd_mailrelay_table_item }}.j2
    dest: /etc/smtpd/tables/{{ opensmtpd_mailrelay_table_item }}
    owner: root
    group: opensmtpd
    mode: "0640"
  notify: restart opensmtpd
  with_items:
    - relay_secrets
    - monitoring_from
    - monitoring_recipients
  loop_control:
    loop_var: opensmtpd_mailrelay_table_item

- name: template /etc/mailname
  template:
    src: "templates/etc/mailname.j2"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart opensmtpd

- name: Configure rsyslog for OpenSMTPD
  template:
    src: templates/etc/rsyslog.d/opensmtpd.conf.j2
    dest: /etc/rsyslog.d/opensmtpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: restart rsyslog