- name: send test mails from all defined accounts
  shell: |
      {% for mailrelay_opensmtpd_relay in mailrelay_opensmtpd_relays %}
      {% for mailrelay_opensmtpd_relay_from in mailrelay_opensmtpd_relay['from'] %}
      echo "Testmail from $(hostname -f)" | mail -a "From: {{ mailrelay_opensmtpd_relay_from }}" -s "Testmail from $(hostname -f)" {{ mailrelay_testmail_recipient }}
      {% endfor %}
      {% endfor %}
  args:
    executable: /bin/bash
  when: mailrelay_opensmtpd_relays != []

- name: send test mail via monitoring (smtp-to-matrix)
  shell: |
      echo "Monitoring testmail from $(hostname -f)" | mail -a "From: monitoring@example.com" -s "Monitoring testmail from $(hostname -f)" {{ mailrelay_testmail_recipient }}
  args:
    executable: /bin/bash

- name: wait a bit for mailq to clear
  pause:
    seconds: 10

- name: run smtpctl show queue
  shell: "smtpctl show queue | wc -l"
  register: mailrelay_opensmtpd_send_test_mail_queue_output

- name: run smtpctl show queue output
  debug:
    msg: "{{ mailrelay_opensmtpd_send_test_mail_queue_output.stdout_lines }}"
