winusers_list_fti_app2:

  SA_AQUSER1:
    password_never_expires: true

  SA_AQUSER2:
    password_never_expires: true

  SA_AQUSER3:
    password_never_expires: true

  RA_AQUSER1:
    password_never_expires: true
