winserver_roles_enabled_wserver3:
  net35: true
  net45: true
  net46: true
  port_sharing: true
  rdpserver: false
  defender: true
  ad-domain-services: true
  dns: true
  rsat-adds: true
  rsat-dns-server: true
  gpmc: true