---
- name: Configure ansible user sudoers
  hosts: all
  become: true
  tasks:
    - name: Create ansible sudoers file
      copy:
        content: "ansible ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/ansible
        mode: '0440'
        owner: root
        group: root
        validate: /usr/sbin/visudo -cf %s