## Role: geerlingguy.firewall
## -------------------------

firewall_allowed_tcp_ports_hetzner1:
  - "22" # ssh port 
  - "25" # this is only accessible from inside networks (podman), as ionos has a firewall for world connections, to proctect us
  - "443" # web server, ha proxy
  # - "31222" # modfied ssh port, after bootstrap - not on hetzner
  - "3306" # mysql, internal
  - "3443" # fwproxy, internal
  - "3444" # conapi, internal
  - "2085" # forgejo UI
  - "2222" # forgejo SSH/GIT
  - "4646" # nomad ui, internal
  - "8080" # mitm proxy
  - "8081" # mitm proxy ui
  - "8888" # mitm proxy
  - "8889" # mitm proxy ui

firewall_allowed_udp_ports_hetzner1:
  - "51820" # wireguard
