lego_acme:  "{{ lookup('community.general.merge_variables', 'lego_acme_', pattern_type='prefix', override='ignore') }}"
lego_acme_all:
  image_version: lego_acme:v4.22
  email: robert.thurnreiter@schmetterling.de
