# role-mailrelay-opensmtpd
wg_mesh_aliases: []
internal_private_domain_name: smg-air-conso.vm
internal_private_domain_tld: vm
internal_private_domain: smg-air-conso.vm
internal_private_domain_underscore: la_cuna_vm
# internally used public domain, reachable publicly, has public DNS records
internal_public_domain_name: smg-air-conso.de
internal_public_domain_tld: de
internal_public_domain: smg-air-conso.de
internal_public_domain_underscore: smg_air_conso_de

default_email_from: technology@smg-air-conso.de