win_hostname: SMG-TST-F01

policy_settings_registry_windows_rdp_fserver1:
  cAdministrativeTemplateSetting:

#https://gpsearch.azurewebsites.net/Default.aspx?PolicyID=2513#2488
    - policytype: "Machine"
      keyvaluename: "Software\\Policies\\Microsoft\\Windows NT\\Terminal Services\\LicenseServers"
      type: "String"
      data: "SMG-TST-F01"

#https://gpsearch.azurewebsites.net/Default.aspx?PolicyID=2513#2488
    - policytype: "Machine"
      keyvaluename: "Software\\Policies\\Microsoft\\Windows NT\\Terminal Services\\LicensingMode"
      type: "Dword"
      data: 4
