win_hostname: SMG-SCA-T01

policy_settings_registry_windows_rdp_tserver1:
    cAdministrativeTemplateSetting:
#https://gpsearch.azurewebsites.net/Default.aspx?PolicyID=2513#2488
    - policytype: "Machine"
      keyvaluename: "Software\\Policies\\Microsoft\\Windows NT\\Terminal Services\\LicenseServers"
      type: "String"
      data: "t01.smg-air-conso.com"
