win_hostname: SMG-SCA-W02

policy_settings_registry_windows_rdp_wserver2:
## --------------------------------------------
    cAdministrativeTemplateSetting:

#https://gpsearch.azurewebsites.net/Default.aspx?PolicyID=2513#2488
    - policytype: "Machine"
      keyvaluename: "Software\\Policies\\Microsoft\\Windows NT\\Terminal Services\\LicenseServers"
      type: "String"
      data: "SMG-SCA-T01"
#https://gpsearch.azurewebsites.net/Default.aspx?PolicyID=2513#2488
    - policytype: "Machine"
      keyvaluename: "Software\\Policies\\Microsoft\\Windows NT\\Terminal Services\\LicensingMode"
      type: "Dword"
      data: 4

ad_servers_list:
  - SMG-SCA-W02

ad_domain_server: SMG-SCA-D01 #d01.smg-air-conso.com
ad_domain_server_ip: 10.6.1.98

js7_jobssh_user_dir: RA_AQUSER1
js7_jobssh_user_allow: 'Administrator SMG-AIRCONSO\RA_AQUSER1'
js7_jobssh_pub_key: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIaR88s1+JtgEBc8C3IvfF3BICPaff8NuNrknm/fLCMb9wKsVJN2B0SVnKHgCvV7hZmBEF4Dvq9RFTgvz4kwYXg="
