## See https://stackoverflow.com/questions/16221250/add-a-key-to-hkey-current-user-for-all-users
## to add registry setting per user once

airquest_defaults_prd:
  enabled: true
  automount: false
  host: SMG-TST-F01
  host_ip: 192.168.121.51
  drive_letter: Q
  share: proquest
  local_path: "d:\\proquest"
  user: SMG-TST-F01\SA_AQUSER1
  host_dev: SMG-TST-F01
  host_ip_dev: 192.168.121.51
  drive_letter_dev: S
  share_dev: proquest.dev