cnf_js7_server_default:
  joc_external_port: 4446
  controller_external_port: 4444
  controller_health_port: 8000
  agent_external_port: 4445
  agent_health_port: 8001
  agent_external_port_secondary: 4485
  agent_health_port_secondary: 8002
  public_ip: l03.smg-air-conso.com
