## Role:-mailrelay-opensmtpd
## ------------------------
# Hostname for this mailrelay - should not be the servers actual hostname
# Commonly just the domain of the company running the server
# Will be written into the header of all outgoing emails
# Has to be an existing mailserver with a MX record
mailrelay_opensmtpd_mailname: smg-air-conso.de

monitoring_email_sender: technology@smg-air-conso.de
mailrelay_default_sender_user: 86b734001@smtp-brevo.com
mailrelay_opensmtpd_monitoring_linux_users:
  - root
  - www-data
  - mysql
  - apache
  - "root@{{ mailrelay_opensmtpd_mailname }}"
  - "{{ monitoring_email_sender }}"
  - monitoring@example.com
  - devops@smg-air-conso.de
  
# List of relay information
mailrelay_opensmtpd_relays_default:
  - alias: smg-air-conso.de
    server: "smtp-relay.brevo.com"
    mail-from: "{{ default_email_from }}"
    protocol: "smtp+tls"
    tls: True
    port: "587"
    login: "{{ mailrelay_default_sender_user }}"
    password: "{{ mailrelay_default_sender_password }}"
    from: "{{ mailrelay_opensmtpd_monitoring_linux_users }}"
# Combine lists of relays
# SETUP #
mailrelay_opensmtpd_relays: "{{ mailrelay_opensmtpd_relays_default + mailrelay_opensmtpd_relays_custom | default([]) }}"

# Send warning messages on delay mails
# Set to False to disable
mailrelay_opensmtpd_smtpd_conf_bounce_warn_interval: 300s
mailrelay_to_matrix: false

#mailrelay_smtp_to_matrix_username: "matrix-username" # without @ or :matrix.org !
#mailrelay_smtp_to_matrix_password: "secret-password"
#mailrelay_smtp_to_matrix_server: "https://matrix.org"
#mailrelay_smtp_to_matrix_room_id: "!YOUR_MATRIX_ROOM_ID:matrix.org"
