- hosts: all
  become: true
  gather_facts: true

  vars_files:
  - main/vars.yml

  roles:
    - geerlingguy.firewall
    - weareinteractive.apt

  pre_tasks:

  - import_tasks: set_ubuntu_mirror_pre_task.yml

  - name: Ensure ntpdate is installed
    apt:
      name: ntpdate
      state: present

  - name: Synchronize time with NTP server
    command: ntpdate pool.ntp.org
    become: true
    when: ntpdate_enabled is defined and ntpdate_enabled == true

  - name: Synchronize time with www.google.de server
    shell: "date -s \"$(curl -sI https://google.com | grep -i ^Date: | cut -d' ' -f3-6)Z\""
    become: true
    when: curldate_enabled is defined and curldate_enabled == true


  - name: Update apt cache if needed.
    apt: update_cache=yes cache_valid_time=3600

  handlers:
  - import_tasks: handlers/handlers.yml

  tasks:
  - name: run role geerlingguy.security
    include_role:
      name: geerlingguy.security
      tasks_from: main.yml
    when: geerlingguy_security_enabled is defined and geerlingguy_security_enabled == true

  - name: run role geerlingguy.firewall
    include_role:
      name: geerlingguy.firewall
      tasks_from: main.yml
    when: geerlingguy_firewall_enabled is defined and geerlingguy_firewall_enabled == true

  - name: Install Linux groups
    include_role:
      name: arillso.system.groups

  - name: Install Linux users
    include_role:
      name: users_with_keys

  - import_tasks: tasks/default_user.yml

  - import_tasks: tasks/nomad.yml
  
  - import_tasks: tasks/fti.yml

  - name: install mailrelay
    include_role:
      name: role-mailrelay-opensmtpd
      tasks_from: main.yml
    when: mailrelay_enabled is defined and mailrelay_enabled == true

  - name: install nullmailer
    include_role:
      name: lifeofguenter.nullmailer
    when: nullmailer_enabled is defined and nullmailer_enabled == true

  - import_tasks: tasks/mariadb.yml
    when: mariadb.enabled is defined and mariadb.enabled == true

  - name: install wireguard
    include_role:
      name: githubixx.ansible_role_wireguard
    when: wireguard_enabled is defined and wireguard_enabled == true

  - import_tasks: tasks/rinetd.yml
    when: port_forwarding.enabled is defined and port_forwarding.enabled == true

  - import_tasks: tasks/mount_q.yml
    when: airquest_defaults.enabled is defined and airquest_defaults.enabled == true
 

