- hosts: all
  become: true
  gather_facts: true

  vars_files:
  - main/vars.yml

  roles:
    - arillso.system.groups
    - arillso.system.users
    - geerlingguy.firewall
    - weareinteractive.apt

  pre_tasks:
  
  - name: Ensure ntpdate is installed
    apt:
      name: ntpdate
      state: present

  - name: Synchronize time with NTP server
    command: ntpdate pool.ntp.org
    become: true
    when: ntpdate_enabled is defined and ntpdate_enabled == true

  - name: Update apt cache if needed.
    apt: update_cache=yes cache_valid_time=3600

  handlers:
  - import_tasks: handlers/handlers.yml

  tasks:
  - name: run role geerlingguy.security
    include_role:
      name: geerlingguy.security
      tasks_from: main.yml
    when: geerlingguy_security_enabled is defined and geerlingguy_security_enabled == true

  - name: run role geerlingguy.firewall
    include_role:
      name: geerlingguy.firewall
      tasks_from: main.yml
    when: geerlingguy_firewall_enabled is defined and geerlingguy_firewall_enabled == true

  - import_tasks: tasks/default_user.yml

  - import_tasks: tasks/nomad.yml
  
  - import_tasks: tasks/fti.yml

  - name: install mailrelay
    include_role:
      name: role-mailrelay-opensmtpd
      tasks_from: main.yml
    when: mailrelay_enabled is defined and mailrelay_enabled == true

  - name: install nullmailer
    include_role:
      name: lifeofguenter.nullmailer
    when: nullmailer_enabled is defined and nullmailer_enabled == true

  - import_tasks: tasks/mariadb.yml
