- hosts: all
  become: true
  become_method: runas
  become_user: Administrator
  gather_facts: false

  vars_files:
  - main/vars.yml

  tasks:
#  - import_tasks: tasks/nomad.yml
#- percona db server

  - name: Include update Timezone
    include_tasks: win-tasks/timezone.yml

  - name: Include tasks SSHD
    include_tasks: win-tasks/sshd.yml
