- hosts: all
  become: true
  gather_facts: true

  vars_files:
  - main/vars.yml

  tasks:
#  - import_tasks: tasks/nomad.yml
#- percona db server
  - name: Include tasks nomad-percona if nomad_percona.enabled is defined
    include_tasks: tasks/nomad/percona.yml
    when: nomad_percona.enabled is defined and nomad_percona.enabled is true
