- name: Create {{ nomad_forgejo.job_name }} log directory
  file:
    path: "{{ nomad_log_dir }}/{{ nomad_forgejo.job_name }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0775"
    recurse: yes

- name: Create application volume and dirs {{ nomad_forgejo.job_name }}
  file:
    path: "{{ forgejo.app_volume }}/data"
    state: directory
    owner: 1000
    group: 1000
    mode: "0775"
    recurse: yes
  loop:
    - data

- name: Manage Nomad job file {{ nomad_forgejo.job_name }}
  template:
    src: nomad-files/forgejo/forgejo.nomad.j2
    dest: "{{ nomad_data_dir }}/jobs/{{ nomad_forgejo.job_name }}.nomad"
    owner: nomad
    group: nomad
    mode: "0644"
  vars:
    job_name: "{{ nomad_forgejo.job_name }}"
    datacenter: "{{ nomad_datacenter }}"
    hostname: "{{ ansible_hostname }}"
    config_dir: "{{ nomad_data_dir }}/jobs/{{ nomad_forgejo.job_name }}"

- name: "Manage Nomad job file {{ nomad_forgejo.job_name }}"
  run_once: true
  nomad_job:
    url: "{{ nomad_server_url }}"
    validate_certs: false
    management_token: "{{ nomad_acl_management_token }}"
    state: present
    namespace: default
    hcl_spec: "{{ lookup('template', 'nomad-files/forgejo/forgejo.nomad.j2') }}"
  vars:
    job_name: "{{ nomad_forgejo.job_name }}"
    datacenter: "{{ nomad_datacenter }}"
    hostname: "{{ ansible_hostname }}"
    config_dir: "{{ nomad_data_dir }}/jobs/{{ nomad_forgejo.job_name }}"
  register: forgejo_nomad_file_changed

- name: "Check Forgejo service status http://{{ nomad_advertise_address }}:{{ forgejo.external_port }}/"
  uri:
    url: "http://{{ nomad_advertise_address }}:{{ forgejo.external_port }}/"
    method: GET
    status_code: 200
  ignore_errors: true
  until: forgejo_status.status == 200
  retries: 2
  delay: 10
  register: forgejo_status