- name: Create {{ nomad_js7.job_name }} log directory
  file:
    path: "{{ nomad_log_dir }}/{{ nomad_js7.job_name }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0777"
    recurse: yes

- name: Create application volume and dirs {{ nomad_js7.job_name }}
  file:
    path: "{{ js7.app_volume }}/data/{{ item }}"
    state: directory
    owner: 1000
    group: 1000
    mode: "0777"
    recurse: yes
  loop:
    - log-joc
    - log-controller
    - controller-primary
    - agent-primary
    - config
    - certs

- name: js7 Create global-server-nomad.pem
  copy:
    src: "{{nomad_certs}}.certs/global-server-nomad.pem"
    dest: "{{ js7.app_volume }}/data/certs/server.pem"
    owner: 1000
    group: 1000
    mode: '0775'
  become: true

- name: js7 copy joc config
  copy:
    src: nomad-files/js7/joc/config/
    dest: "{{ js7.app_volume }}/data/config/joc/"
    owner: 1000
    group: 1000
    mode: '0775'
  become: true

- name: js7 Create config
  template:
    src: nomad-files/js7/joc/config/hibernate.cfg.xml
    dest: "{{ js7.app_volume }}/data/config/joc/hibernate.cfg.xml"
    owner: 1000
    group: 1000
    mode: '0775'
  become: true

- name: js7 copy controller config
  copy:
    src: nomad-files/js7/controller/
    dest: "{{ js7.app_volume }}/data/controller-primary/"
    owner: 1000
    group: 1000
    mode: '0775'
  become: true

- name: js7 Create global-server-nomad-key.pem
  copy:
    src: "{{nomad_certs}}.certs/global-server-nomad-key.pem"
    dest: "{{ js7.app_volume }}/data/certs/server-key.pem"
    owner: 1000
    group: 1000
    mode: '0775'
  become: true

- name: Manage Nomad job file {{ nomad_js7.job_name }}
  template:
    src: nomad-files/js7/js7.nomad.j2
    dest: "{{ nomad_data_dir }}/jobs/{{ nomad_js7.job_name }}.nomad"
    owner: 1000
    group: 1000
    mode: "0644"
  vars:
    job_name: "{{ nomad_js7.job_name }}"
    datacenter: "{{ nomad_datacenter }}"
    hostname: "{{ ansible_hostname }}"
    config_dir: "{{ nomad_data_dir }}/jobs/{{ nomad_js7.job_name }}"

- name: "Manage Nomad job file {{ nomad_js7.job_name }}"
  run_once: true
  nomad_job:
    url: "{{ nomad_server_url }}"
    validate_certs: false
    management_token: "{{ nomad_acl_management_token }}"
    state: present
    namespace: default
    hcl_spec: "{{ lookup('template', 'nomad-files/js7/js7.nomad.j2') }}"
  vars:
    job_name: "{{ nomad_js7.job_name }}"
    datacenter: "{{ nomad_datacenter }}"
    hostname: "{{ ansible_hostname }}"
    config_dir: "{{ nomad_data_dir }}/jobs/{{ nomad_js7.job_name }}"
  register: js7_nomad_file_changed

- name: "Check js7 service status http//{{ nomad_advertise_address }}:{{ js7.controller_health_port }}/"
  uri:
    url: "http//{{ nomad_advertise_address }}:{{ js7.controller_health_port }}/"
    method: GET
    status_code: 200
    validate_certs: no
  ignore_errors: true
  until: js7_status.status == 200
  retries: 3
  delay: 20
  register: js7_status