- name: Create {{ nomad_suitecrm.job_name }} log directory
  file:
    path: "{{ nomad_log_dir }}/{{ nomad_suitecrm.job_name }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0775"
    recurse: yes

- name: Create configuration volume {{ nomad_suitecrm.job_name }}
  file:
    path: "{{ nomad_data_dir }}/jobs/{{ nomad_suitecrm.job_name }}/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0775"
    recurse: yes
  loop:
    - config

- name: Create application volume and dirs {{ nomad_suitecrm.job_name }}
  file:
    path: "{{ suitecrm.app_volume }}/{{ item }}"
    state: directory
    owner: 1
    group: 1
    mode: "0775"
    recurse: yes
  loop:
    - OAuth2
    - backup
    - scripts
    - data

# => https://hub.docker.com/r/bitnami/suitecrm
- name: Copy api private.key
  copy:
    src: nomad-files/suitecrm/private.key
    dest: "{{ suitecrm.app_volume }}/OAuth2/private.key"
    owner: 1
    group: 1
    mode: "0640"

- name: Copy api public.key
  copy:
    src: nomad-files/suitecrm/public.key
    dest:  "{{ suitecrm.app_volume }}/OAuth2/public.key"
    owner: 1
    group: 1
    mode: "0777"

- name: Copy deploy_oauth_keys
  copy:
    src: nomad-files/suitecrm/deploy_oath_key.sh
    dest: "{{ suitecrm.app_volume }}/scripts/deploy_oath_key.sh"
    owner: 1
    group: 1
    mode: "0640"

- name: Manage Nomad job file {{ nomad_suitecrm.job_name }}
  template:
    src: nomad-files/suitecrm/suitecrm.nomad.j2
    dest: "{{ nomad_data_dir }}/jobs/{{ nomad_suitecrm.job_name }}.nomad"
    owner: nomad
    group: nomad
    mode: "0644"
  vars:
    job_name: "{{ nomad_suitecrm.job_name }}"
    datacenter: "{{ nomad_datacenter }}"
    hostname: "{{ ansible_hostname }}"
    config_dir: "{{ nomad_data_dir }}/jobs/{{ nomad_suitecrm.job_name }}"

- name: "Manage Nomad job file {{ nomad_suitecrm.job_name }}"
  run_once: true
  nomad_job:
    url: "{{ nomad_server_url }}"
    validate_certs: false
    management_token: "{{ nomad_acl_management_token }}"
    state: present
    namespace: default
    hcl_spec: "{{ lookup('template', 'nomad-files/suitecrm/suitecrm.nomad.j2') }}"
  vars:
    job_name: "{{ nomad_suitecrm.job_name }}"
    datacenter: "{{ nomad_datacenter }}"
    hostname: "{{ ansible_hostname }}"
    config_dir: "{{ nomad_data_dir }}/jobs/{{ nomad_suitecrm.job_name }}"
  register: suitecrm_nomad_file_changed

- name: Check SuiteCRM service status
  uri:
    url: "http://{{ nomad_advertise_address }}:{{ suitecrm.external_port }}/#/Login"
    method: GET
    status_code: 200
  ignore_errors: true
  until: suitecrm_status.status == 200
  retries: 2
  delay: 10
  register: suitecrm_status