airquest_fileserver_default:
  host: "{{ airquest_defaults.host }}"
  host_name: "{{ airquest_defaults.host_name }}"
  host_name_dev: "{{ airquest_defaults.host_name_dev }}"
  drive_letter: "{{ airquest_defaults.drive_letter }}" 
  drive_letter_dev: "{{ airquest_defaults.drive_letter_dev }}" 
  share: "{{ airquest_defaults.share }}"
  share_dev: "{{ airquest_defaults.share_dev }}"
  local_path: "{{ airquest_defaults.local_path }}"
  user: "{{ airquest_defaults.user }}"
  password: "{{ airquest_defaults.password }}"

  registry_absent:
    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Layers"
      vname: "C:\\Windows\\System32\\Taskmgr.exe"

    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
      vname: "legalnoticecaption"

    - key: "HKEY_LOCAL_MACHINESOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
      vname: "legalnoticetext"

  registry_present:
    - key: "HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
      vname: "HideFileExt"
      vtype: "Dword"
      vdata: 0
# HKLM\software\microsoft\windows\current version\explorer\advanced\folder
    - key: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"
      vname: "HideFileExt"
      vtype: "Dword"
      vdata: 0

    - key: "HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced\\Folder"
      vname: "HideFileExt"
      vtype: "Dword"
      vdata: 0

    - key: "HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap\\Ranges\\Range10000"
      vname: "file"
      vtype: "Dword"
      vdata: 1

    - key: "HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap\\Ranges\\Range10000"
      vname: ":Range"
      vtype: "String"
      vdata: "{{ airquest_defaults.host_name }}"

    - key: "HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMapKey"
      vname: "file://{{ airquest_defaults.host_name }}"
      vtype: "String"
      vdata: 1

    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\System"
      vname: "EnableLinkedConnections"
      vtype: "Dword"
      vdata: "1"

    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\AppCompatFlags\\Layers"
      vname: "C:\\Windows\\System32\\Taskmgr.exe"
      vtype: "String"
      vdata: "RUNASINVOKER"

    - key: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      vname: "__compat_layer"
      vtype: "String"
      vdata: "DISABLETHEMES"

## See https://stackoverflow.com/questions/16221250/add-a-key-to-hkey-current-user-for-all-users
## to add registry setting per user once

    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components\\aq_cli_autostart"
      vname: "Version"
      vtype: "String"
      vdata: "3"

    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components\\aq_cli_autostart"
      vname: "StubPath" 
      vtype: "String"
      vdata: "reg add HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v \"aq_cli_autostart\" /d \"d:\\batch\\aq_cli.cmd -c automation_start POST_LOGON\" /t REG_SZ /f"
      
    - key: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      vname: "AQ_FILE_SERVER_IP" 
      vtype: "String"
      vdata: "{{ airquest_defaults.host_name }}"

    - key: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      vname: "AQ_FILE_SERVER_HOST" 
      vtype: "String"
      vdata: "{{ airquest_defaults.host }}"

    - key: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      vname: "AQ_FILE_SERVER_SHARE" 
      vtype: "String"
      vdata: "{{ airquest_defaults.share }}"

    - key: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      vname: "AQ_FILE_SERVER_SHARE_DEV" 
      vtype: "String"
      vdata: "{{ airquest_defaults.share_dev }}"

    - key: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      vname: "AQ_FILE_SERVER_NETUSR" 
      vtype: "String"
      vdata: "{{ airquest_defaults.user }}"

    - key: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      vname: "AQ_FILE_SERVER_NETPWD" 
      vtype: "String"
      vdata: "{{ airquest_defaults.password }}"

    - key: "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
      vname: "AQTMP" 
      vtype: "String"
      vdata: "D:\\DATA\\AQ-TEMP"

# https://serverfault.com/questions/788463/why-is-sitetozoneassignment-gpo-applying-but-sites-not-appearing-in-ie
# https://github.com/js1016/MapUrlToZone?tab=readme-ov-file
# HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap
    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap"
      vname: "IEHarden"
      vtype: "Dword"
      vdata: 0

    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap"
      vname: "IEHarden"
      vtype: "Dword"
      vdata: 0

# HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap
    - key: "HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap"
      vname: "rhor"
      vtype: "Dword"
      vdata: 1

    - key: "HKEY_LOCAL_MACHINE\\Software\\Policies\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap"
      vname: "rhor"
      vtype: "Dword"
      vdata: 1
